### ISSUE TITLE
launch checklist

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#152]
@rcar1115 thought its a good idea to list all the bits'n'bobs that we will need to check for once live:
- [x] switch the subscribe success page over
- [x] enable the fonts to the paid version
- [x] charge LWA for fontdeck and take their CC details
- [x] backdate monotype fonts with fonts.com
- [x] retest category page links
- [x] update shopify theme
- [x] archive previous application
